### ISSUE TITLE
Duplicate images in folders

### ISSUE THREAD

**Issue by VoodooHillbilly** [Deji69/Croupier#12]
There's some duplicate files that seem to be left over from converting everything to JPEG.

`/actors/default_target.dds`
`/actors/default_target_briefing.dds`
`/actors/default_target_portrait.dds`
`/outfits/haven-butler.png`

This one may not matter, but I noticed the new `/methods/impact_explosive.png` is a huge 3328 × 2483 and 4MB. Most of the other `/methods/condition_killmethod_*.jpg` files are 693 × 517.

**Comment by Deji69** [comment]
Oversized impact explosive image is probably the one that matters most and is fixed in in 2.3.

**Comment by VoodooHillbilly** [comment]
Ok. I wasn't 100% sure if the others were still there for a reason or not.
